

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#     "blog_id": "Title-1FVuRewb1AlrzCFPw9RJRF"
# }

GET http://localhost:3000/new-notification
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWE4ZDUwMWIwYTYyYzhiMzQ4NmE4MCIsImlhdCI6MTcwNjcyNzk3MX0.AG_gz-GPE11fLEaS2yMx2_1RzEfhAlKVQ2ICsDLC1Hk



# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email": "jay@gmail.com",
#     "password": "Welekar@2003"
# }